name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: build OC_teensy40
      run: |
        git submodule update --init
        pio run -e OC_teensy40
        export hash=$(git rev-parse --short HEAD)
        mv .pio/build/*/firmware.hex ./firmware_OC_T40_$hash.hex
        mv .github/workflows/LICENSE.txt ./LICENSE.txt
        zip -j ./firmware_OC_T40_$hash.zip ./firmware_OC_T40_$hash.hex ./LICENSE.txt
        curl -f -X PUT -u ${{ secrets.UPLOAD_KEY }} ${{ secrets.LATEST_DROP_FOLDER }}/firmware_OC_T40_latest.zip --upload-file ./firmware_OC_T40_$hash.zip
        curl -f -X PUT -u ${{ secrets.UPLOAD_KEY }} ${{ secrets.LATEST_DROP_FOLDER }}/firmware_latest.sha -d "$hash"
    - name: firmware_artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmware-${{ github.sha }}
        path: |
          ./firmware*.hex
          ./LICENSE.txt
    - name: Test
      run: |
        pio lib install
        sh ./test/test.sh
    - name: test.wav
      uses: actions/upload-artifact@v2
      with:
        name: test_waves
        path: .test/*.wav